# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-19 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200419_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='identifier',
            field=models.CharField(default='', max_length=40, unique=True),
        ),
    ]
