# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-19 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='identifier',
        ),
    ]
